---
title: "SOM: Modern stone tool users from Northern Kenya emphasize mass and edge length in the selection of cutting tools"
subtitle: "Tables"
author: "Jonathan S. Reeves"
date: "`r Sys.Date()`"
output: tint::tintPdf
bibliography: skeleton.bib
link-citations: yes
---

# Load Packages
```{r setup, include=FALSE}
library(dplyr)
```

# Load Data 
```{r}

lithics <- read.csv("Data/CE_Lithics_all.csv")
lithics$Participant <- as.numeric(as.factor(lithics$Participant))



```

# SOM Table 1: Summary of the mass and cutting edge length according to technological type
```{r SOM table 1}
CE  <- read.csv("Data/CE_cutting_edges.csv")

edge_break_down <- CE %>%
  group_by(Type) %>%
  summarise(Median_Mass = median(Mass, na.rm = TRUE),
            Median_Cutting_Edge_Length = median(cutting_edge))

write.csv(edge_break_down, "Tables/SOM_T1_Cutting_edge_length.csv")
```

# SOM Table 2: Number of lithics produced according to participant and raw material

The totals and breakdown by materials are compiled into a table in the SI document. 
```{r SOM table 2}

particip_totals <- lithics %>% 
  group_by(Participant) %>%
  summarise(N = n())
  
particip_rm <- lithics %>% 
  group_by(Participant, Raw_Material) %>%
  summarise(N = n())

write.csv(particip_rm, "Tables/SOM_T2_RM_Particip.csv")

```

```{r SOM table 3}

particip_break_down <- lithics %>% 
  group_by(Participant, Context) %>%
  summarise(N = n())

write.csv(particip_break_down, "Tables/SOM_T3_Selection_Particip.csv")


```








