---
title: "SOM Modern stone tool users provide insight into selection criteria of cutting tools"
subtitle:"Figures"
author: "Jonathan S. Reeves"
date: "`r Sys.Date()`"
---

# Load packages

```{r setup, include=FALSE}

library(ggplot2)
library(forcats)
library(ggtext)
library(colorspace)
library(ragg)
library(rethinking)
library(ggpubr)
source("Helper_functions.R")

```

```{r load data}

lithics <- read.csv("Data/CE_Lithics_all.csv")
xdata <- read.csv("Data/CE_cutting_edges.csv")
global_model <- readRDS("Models/CE_Global_Model.RDS")

```

# Main Text Figures

## Figure 1

Figure 1 is a compilation of photos taken during fieldwork. No R code was used in its creation. 

## Figure 2

Figure 2 is a picture of lithics from the various phases of selection. No R code was used in their creation.

## Figure 3

```{r fig3"}

cols <- c("#F21A00","#78B7C5","#3B9AB2", "#EBCC2A", "#E1AF00")

f3 <- ggplot(lithics, aes(x = Context, group = Type, fill = Type)) + 
  geom_bar(position = "fill") +
  guides(fill = guide_legend(ncol = 2))+
  scale_fill_manual(values = cols)+
  labs(x = "Selection Stage", y = "Cumulative Freq.")+
  guides(fill= guide_legend(nrow = 1))+
  theme_bw()+
  theme(legend.position = "top",)

f3

ggsave("Figures/CE_fig_3.png", plot = f3, width = 7, height = 7, units = "in")

```

## Figure 4

```{r fig3}

alpha <- .5

cols <- c("#B40F20",
          "#DD8D29",
          "#E2D200",
          "#46ACC8")

a <- ggplot(xdata, aes(x = as.factor(Context), y = Mass^(1/3))
            ) +
  ggdist::stat_halfeye(
    aes(color = as.factor(Context),
        fill = after_scale(lighten(color, .2))), ,
        adjust = .5, 
        width = .75, 
        justification = -.4, 
        point_color = NA
    ) +
  geom_boxplot(
    aes(color = stage(as.factor(Context),
                      after_scale = darken(color, .1, space = "HLS")),
        fill = after_scale(desaturate(lighten(color, .8), .4))),
    width = .42, 
    outlier.shape = NA
  ) + 
    geom_point(
      aes(color = stage(as.factor(Context), 
                        after_scale = darken(color, .4, space = "HLS"))),
      fill = "white",
      shape = 21,
      stroke = .4,
      size = 2,
    position = position_jitter(seed = 1, width = .12)
    )+
  scale_color_manual(values = cols
    )+ 
  labs(x = "",y= "Mass (g, cubed root)"
    ) + 
   coord_flip(xlim = c(1.2, NA), clip = "off"
              ) +
  theme_bw()+
  theme(legend.position = "none",
        axis.title.y = element_blank(),
        axis.text.y = element_blank())

b <- ggplot(xdata, aes(x = as.factor(Context), y = cutting_edge)
            ) +
  ggdist::stat_halfeye(
    aes(color = as.factor(Context),
        fill = after_scale(lighten(color, .2))),
        adjust = .5, 
        width = .75, 
        .width = 0,
        justification = -.4, 
        point_color = NA
    ) +
  geom_boxplot(
    aes(color = stage(as.factor(Context),
                      after_scale = darken(color, .1, space = "HLS")),
        fill = after_scale(desaturate(lighten(color, .8), .4))),
    width = .42, 
    outlier.shape = NA
  ) + 
    geom_point(
      aes(color = stage(as.factor(Context), 
                        after_scale = darken(color, .4, space = "HLS"))),
      fill = "white",
      shape = 21,
      stroke = .4,
      size = 2,
    position = position_jitter(seed = 1, width = .12)
    )+
  scale_color_manual(values = cols
    )+ 
  labs(x = "Selection Stage",y= "Cutting Edge Length"
    ) + 
  coord_flip(xlim = c(1.2, NA), clip = "off"
              ) +
  theme_bw()+
  theme(legend.position = "none")
b 

f4 <- ggpubr::ggarrange(b,a)

ggsave("Figures/CE_fig_4.pdf", plot = f4, width = 7, height = 4, units = "in")

f4
```


## Figure 5

```{r fig Cutting Edge Length, echo = FALSE, fig.width=13}

min_val <- min(xdata$cutting_edge)
max_val <- max(xdata$cutting_edge)

xvar <- seq(min_val, 
          max_val, 
          by = .25)

kM <-  min(xdata$M)
kEL <- xvar
kEA <- mean(xdata$mean_angle)
kTh <- mean(xdata$Max_Thick)
kC <- .5

var_quant <- c(5, 34, 125 )^(1/3)

cols <- c( "Stage 1"= "#B40F20",
                       "Stage 2" = "#DD8D29",
                       "Stage 3" = "#E2D200",
                       "Stage 4" = "#46ACC8")

plots <- list()

for(i in 1:length(var_quant)){
  kM <- var_quant[i]
  sim_dat <- data.frame(M=kM,
                      L=kEL,
                      EL = kEL,
                      Th= kTh,
                      EA = kEA,
                      C = kC)
  
p <- ggPostPredPlot_pordlogit(model = global_model,
                       sim = sim_dat,
                       var = sim_dat$EL, 
                       n_samples = 2000,
                       opac = .3)$sum_plot
 p <- p + 
   scale_x_continuous(expand=c(0,0)) +
   scale_y_continuous(expand=c(0,0)) +
   labs(title = paste("Mass:", var_quant[i]^3, "(g)"),
          x = "Edge Length (cm)",
          y = ifelse(test = i == 1, "Cumulative Prop.", ""),
        fill = "Selection Stage")+
   scale_fill_manual(values = cols)
 
 plots[[i]] <- p
}


f5 <- ggarrange(plotlist = plots[],ncol = 3, 
                label.x = "Cumulative Proportion",
                label.y = "Cutting Edge Length (cm)",common.legend = TRUE, legend = "bottom")


f5 
ggsave("Figures/CE_fig_5.png", plot = f5, width = 10, height = 4, units = "in")


```


**Figure 6**

```{r fig  Cortex, echo = FALSE}
nsamples <- 2000
min_val <- min(0)
max_val <- max(1)

xvar <- seq(min_val, 
          max_val, 
          length.out = 30)

kM <-  mean(xdata$Mass)^(1/3)
kEL <- mean(xdata$cutting_edge)
kEA <- mean(xdata$mean_angle)
kTh <- mean(xdata$Max_Thick)
kC <- xvar

sim_dat <- data.frame(M=kM,
                      EL = kEL,
                      Th= kTh,
                      EA = kEA,
                      C = kC)
  
 p <- ggPostPredPlot_pordlogit(model = global_model,
                       sim = sim_dat,
                       var = sim_dat$C, 
                       n_samples = nsamples,
                       opac = .3)$sum_plot
 c_plot <- p + 
   labs(title = "Cortex",
          x = "% Cortex",
          y = "Cumulative Proportion",
        fill = "Selection stage") + 
      scale_fill_manual(values = cols)
 
c_plot       
```



```{r fig  Thickness, echo = FALSE}
nsamples = 2000
min_val <- min(xdata$Max_Thick)
max_val <- max(xdata$Max_Thick)

xvar <- seq(min_val, 
          max_val, 
          length.out = 50)

kM <-  mean(xdata$Mass^(1/3))
kEL <- mean(xdata$cutting_edge)
kEA <- min(xdata$mean_angle)
kTh <- xvar
kC <- .5

sim_dat <- data.frame(M=kM,
                      EL = kEL,
                      Th= kTh,
                      EA = kEA,
                      C = kC)
  
 p <- ggPostPredPlot_pordlogit(model = global_model,
                       sim = sim_dat,
                       var = sim_dat$Th, 
                       n_samples = nsamples,
                       opac = .3)$sum_plot
 thick_plot <- p + 
   labs(title = "Thickness",
          x = "Thickness (cm)",
          y = "",
        fill = "Selection stage") + 
      scale_fill_manual(values = cols)
   

thick_plot
```


```{r fig  Edge Angle, echo = FALSE}

min_val <- min(xdata$mean_angle)
max_val <- max(xdata$mean_angle)

xvar <- seq(min_val, 
          max_val, 
          length.out = 50)

kM <-  mean(xdata$Mass ^(1/3))
kEL <- mean(xdata$cutting_edge)
kEA <- xvar
kTh <- mean(xdata$Max_Thick)
kC <- .5

sim_dat <- data.frame(M=kM,
                      EL = kEL,
                      Th= kTh,
                      EA = kEA,
                      C = kC)
  
 p <- ggPostPredPlot_pordlogit(model = global_model,
                       sim = sim_dat,
                       var = sim_dat$EA, 
                       n_samples = nsamples,
                       opac = .3)$sum_plot
 edge_plot <- p + 
   labs(title = "Edge Angle",
          x = "Edge Angle (degrees)",
          y = "",
        fill = "Selection stage") + 
      scale_fill_manual(values = cols)

edge_plot

```

```{r fig 5}

f6 <- ggarrange(c_plot, thick_plot, edge_plot,ncol = 3, common.legend = TRUE, legend = "bottom")

ggsave("Figures/CE_fig_6.png", plot = f6, width = 10, height = 4, units = "in")

f6
```

# Supplementary

```{r fig3, fig.cap= "Jitter plots showing the distribution of cutting edge length (left) and mass (right) mass values for each stage of selection. In both cases, there is selection against the lithics with the shortest cutting edge and least mass at each selection stage. \\label{CE_f3}"}

alpha <- .5

a <- ggplot(xdata, aes(x = as.factor(Context), y = Per_Cortex)) + 
  geom_jitter(alpha = alpha)+
  labs(x = "Selection Stage",y= "% Cortex") + 
  theme_bw()

b <- ggplot(xdata, aes(x = as.factor(Context), y = mean_angle)) +
  geom_jitter(alpha = alpha)+ 
  labs(x = "Selection Stage",y= "Avg. Edge Angle") + 
  theme_bw()

c <- ggplot(xdata, aes(x = as.factor(Context), y = Max_Thick)) +
  geom_jitter(alpha = alpha)+ 
  labs(x = "Selection Stage",y= "Max Thickness (mm)") + 
  theme_bw()

SOM_f1 <- ggpubr::ggarrange(b,a,c, ncol = 3)

#ggsave("Figures/SOM_CE_f1_Attirb.pdf", plot = SOM_f1, width = 12, height = 4, units = "in")

SOM_f1
```


## Individal Model Effects

```{r read_model}
indv.model <- readRDS("Models/CE_Participant_Model.RDS")
```

```{r fig Indiv.Mass, echo = FALSE}

min_val <- min(xdata$cutting_edge)
max_val <- max(xdata$cutting_edge)

xvar <- seq(min_val, 
          max_val, 
          by = .25)

kEL <- xvar
kEA <- mean(xdata$mean_angle)
kTh <- mean(xdata$Max_Thick)
kC <- .5

var_quant <- c(5, 40, 300)^(1/3)

Pid <- c(1:8)
plots <- list()
a <- 0

for(id in Pid){

  for(i in 1:length(var_quant)){
    kM <- var_quant[i]
    sim_dat <- data.frame(M=kM,
                      L=kEL,
                      EL = kEL,
                      Th= kTh,
                      EA = kEA,
                      C = kC,
                      P = id)
  
    p <- ggPostPredPlot_pordlogit(model = indv.model,
                       sim = sim_dat,
                       var = sim_dat$EL, 
                       n_samples = 200,
                       cols = cols,
                       opac = .3)$sum_plot
    p <- p + 
   scale_x_continuous(expand=c(0,0)) +
   scale_y_continuous(expand=c(0,0)) +
   labs(title = paste("Mass:", var_quant[i]^3, "(g)"),
          x = "Edge Length (cm)",
          y = ifelse(test = i == 1, "Cumulative Prop.", ""),
        fill = "Selection Stage")+
   scale_fill_manual(values = cols)
      
    a <- a + 1
    plots[[a]] <- p
}
}


indvs <- ggarrange(plotlist = plots,ncol = 3, common.legend = TRUE, legend = "bottom")

for(i in 1:8){
  path <- paste0("Figures/CE_fig_CEM_P_",i,".png")
  ggsave(path, plot = indvs[[i]], width = 10, height = 4, units = "in")
}
```

```{r fig Indiv.cortex, echo = FALSE}

nsamples <- 2000
min_val <- min(0)
max_val <- max(1)

xvar <- seq(min_val, 
          max_val, 
          length.out = 30)

kM <-  mean(xdata$Mass)^(1/3)
kEL <- mean(xdata$cutting_edge)
kEA <- mean(xdata$mean_angle)
kTh <- mean(xdata$Max_Thick)
kC <- xvar


Pid <- c(1:8)
plots <- list()

for(id in Pid){
  
  sim_dat <- data.frame(M=kM,
                      EL = kEL,
                      Th= kTh,
                      EA = kEA,
                      C = kC, 
                      P = id)
  
    p <- ggPostPredPlot_pordlogit(model = indv.model,
                       sim = sim_dat,
                       var = sim_dat$C, 
                       n_samples = 50,
                       cols = cols,
                       opac = .3)$sum_plot
    p <- p + 
         labs(title = paste0("Cortex, Particpant: ",id),
          x = "% Cortex",
          y = "Cumulative Proportion",
        fill = "Selection stage") + 
      scale_fill_manual(values = cols)
    
    plots[[id]] <- p
}


plot <- ggarrange(plotlist = plots, common.legend = TRUE)
ggsave(filename = "Figures/SOM_Cortex_indv.png", 
       plot = plot,
       width = 10,
       height = 11, 
       units = "in")

```


```{r fig Thickness, echo = FALSE}

min_val <- min(xdata$Max_Thick)
max_val <- max(xdata$Max_Thick)

xvar <- seq(min_val, 
          max_val, 
          length.out = 30)

kM <- mean(xdata$Mass^(1/3))
kEL <- mean(xdata$cutting_edge)
kEA <- mean(xdata$mean_angle)
kTh <- xvar
kC <- .5


Pid <- c(1:8)
plots <- list()

for(id in Pid){
  
  sim_dat <- data.frame(M=kM,
                        L=kEL,
                        EL = kEL,
                        Th= kTh,
                        EA = kEA,
                        C = kC,
                        P = id)
  
    p <- ggPostPredPlot_pordlogit(model = indv.model,
                       sim = sim_dat,
                       var = sim_dat$Th, 
                       n_samples = 50,
                       cols = cols,
                       opac = .3)$sum_plot
    p <- p + 
      labs(title = paste0("Thickness, Particpant: ",id),
          x = "Maximum Thickness",
          y = "Cumulative Proportion",
        fill = "Selection stage") + 
      scale_fill_manual(values = cols)
    
    plots[[id]] <- p
}


plot <- ggarrange(plotlist = plots, common.legend = TRUE)
ggsave(filename = "/Figures/SOM_Thickness_indv.png", 
       plot = plot,
       width = 10,
       height = 11, 
       units = "in")


```



```{r fig Edge_angle, echo = FALSE}

min_val <- min(xdata$mean_angle)
max_val <- max(xdata$mean_angle)

xvar <- seq(min_val, 
          max_val, 
          length.out = 30)

kM <- mean(xdata$Mass^(1/3))
kEL <- mean(xdata$cutting_edge)
kEA <- xvar 
kTh <- mean(xdata$Max_Thick)
kC <- .5


Pid <- c(1:8)
plots <- list()

for(id in Pid){
  
  sim_dat <- data.frame(M=kM,
                        L=kEL,
                        EL = kEL,
                        Th= kTh,
                        EA = kEA,
                        C = kC,
                        P = id)
  
    p <- ggPostPredPlot_pordlogit(model = indv.model,
                       sim = sim_dat,
                       var = sim_dat$EA, 
                       n_samples = 50,
                       cols = cols,
                       opac = .3)$sum_plot
    p <- p + 
      labs(title = paste0("Edge Angle, Particpant: ",id),
          x = "Avg. Edge Angle",
          y = "Cumulative Proportion",
        fill = "Selection stage") + 
      scale_fill_manual(values = cols)
    
    plots[[id]] <- p
}


plot <- ggarrange(plotlist = plots, common.legend = TRUE)


ggsave(filename = "Figures/SOM_Edge_angle_indv.png",
       plot = plot,
       width = 10,
       height = 11,
       units = "in")


```