---
title: "SOM Modern stone tool users provide insight into selection criteria of cutting tools"
subtitle: "Participant level model"
author: "Jonathan S. Reeves"
date: "`r Sys.Date()`"
output: tint::tintPdf
bibliography: skeleton.bib
link-citations: yes
---

```{r setup, include=FALSE}
library(tint)
library(rethinking)
# invalidate cache when the package version changes
knitr::opts_chunk$set(tidy = FALSE, cache.extra = packageVersion('tint'))
options(htmltools.dir.version = FALSE)
```

# Load Data

```{r}
xdata <- read.csv("Data/CE_cutting_edges.csv")
```

# Define and Standardize Variables

These code take care of any transformations, scaling or standardization, that is required by the model and then bundles them into a list.

```{r}

dat <- list(
  S = xdata$Context, # Selection Stage
  M = xdata$Mass^(1/3),
  Th = xdata$Max_Thick, # Maximum thickness
  EL = xdata$cutting_edge, # Edge length
  EA = xdata$mean_angle, # Average edge angles
  C = xdata$Per_Cortex,
  P = as.numeric(as.factor(xdata$Participant))
)

```

# Model definition

```{r}

ceM2 <- ulam(
  alist(
    S ~ dordlogit(phi, cutpoints),
    phi <-   a[P] + bMEL*(M*EL) + bTh*Th + bEA*EA + bC*C,
    
    #save> vector[8]:a <<-abar + za*sigma,
    #vector[8]:za ~ normal(0,1),
    
    #priors
    c(bMEL,bTh,bEA,bTh,bC) ~ dnorm(0, 1.5),
    a[P] ~ dnorm(abar, sigma),
    #priors for the priors
      abar ~ normal(0,1),
      sigma ~ exponential(1),
    
    cutpoints ~ dnorm(0, 1.5)
  ), data= dat, chains = 4, cores =4, iter = 2000,
  )




```

## Model Diagnostics 

```{r ceM2.Marg}

ceM2.marg <- precis(ceM2, depth = 2)
ceM2.marg
```


```{r ceM1.Marg.plot, echo = FALSE, fig.margin = TRUE, fig.cap="Marginal distributions for Model ceM1", fig.width=4, fig.height=4}

plot(ceM2.marg)

```

**Trace Plots**

```{r ceM1.Trace plots}
rethinking::traceplot(ceM2)

```

# Write Model

```{r write model}
saveRDS(ceM2, file = "Models/CE_Participant_Model.RDS")
```




